### PR TITLE
add Node 12 support

### PR DESCRIPTION
**Pull request by fgodino**
Updated bindings for breaking changes on Node 10 -> Node 12.

Tested builds against Node 10 and Node 12 on MacOS Big Sur.

### CODE REVIEW

**Review by acoroleu-tempus — APPROVED** [review]

**Comment by fgodino** [comment]
@Mmdixon I see the azure pipeline is not launching correctly. Are you taking any further steps?

**Comment by Mmdixon** [comment]
@fgodino yes I noticed it was targeting a hosted machine that was no longer supported. I updated the build pipelines and added node 12.22 to the tests.

**Pull request merged**
